version: 2.1

orbs:
  orb: invocations/orb@1.5.0

workflows:
  main:
    jobs:
      - orb/lint:
          name: Lint
      - orb/format:
          name: Style check
      - orb/coverage:
          name: Test
      - orb/test-release:
          name: Release test
      - orb/test:
          name: Test << matrix.version >>
          # It's not worth testing on other interpreters if the baseline one
          # failed. Can't run >4 jobs at a time anyhow!
          requires: ["Test"]
          matrix:
            parameters:
              version: ["3.10", "3.11", "3.12", "3.13"]
      - orb/docs:
          name: "Docs"
          requires: ["Test"]
          task: "docs --nitpick"
